name: yogo_pos
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  get: ^4.6.6
  dio: ^5.4.0
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  pagination_flutter: ^0.0.8
  cached_network_image: ^3.4.1
  logger: ^2.4.0

  # printing: ^5.14.0

  intl: ^0.18.0
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  # syncfusion_flutter_pdfviewer: ^27.1.51
  dropdown_textfield: ^1.2.0
  # animated_text_kit: ^4.2.2


  google_fonts: ^6.2.0
  timezone: ^0.10.0
  lottie: ^3.3.0
  syncfusion_flutter_datagrid: ^28.2.9
  toastification: ^3.0.1
  uuid: ^4.5.1
  # flutter_inappwebview: ^6.1.5
  socket_io_client: ^3.0.2
  audioplayers: ^6.1.2
  timelines_plus: ^1.0.6
  fraction: ^5.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.1

# dependency_overrides:
#  printing:
#   git:
#    url: https://github.com/DavBfr/dart_pdf
#    ref: master
#    path: printing
#launcher icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#236AFD"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48

#msix config
msix_config:
  display_name: Yogo Pos
  publisher_display_name: Yogo Pos
  identity_name: com.example.yogo-pos
  msix_version: 1.0.0.0
  logo_path: assets/images/splash/app_icon.png
  capabilities: internetClient

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/icons/
    - assets/icons/auth/
    - assets/audio/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-Italic.ttf
          style: italic
    - family: SfPro
      fonts:
        - asset: assets/sfpro/SFPRODISPLAYBOLD.OTF
          weight: 600
        - asset: assets/sfpro/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/sfpro/SFPRODISPLAYREGULAR.OTF
          weight: 400
